notifications:
    email: false
language: Ruby
rvm:
  - 2.4.0
script:
    - cd test
    - make build_and_run
    - make coverage
    - cd ..
    - cd bindings/ruby
    - bundle install
    - bundle exec rake compile
    - bundle exec rake

    
    
    
